"use client";

import { useState, useEffect } from "react";
import { 
  Settings, Check, Copy, Download, Trash2, Plus, 
  FileText, Search, ShieldCheck, ShieldAlert, RefreshCw, Eye
} from "lucide-react";
import { useToastError, useToastSuccess } from "@/lib/toast";

interface CustomRule {
  userAgent: string;
  type: "allow" | "disallow";
  path: string;
}

export default function RobotsTxtGeneratorPage() {
  const [tab, setTab] = useState<"robots-txt" | "meta-tags" | "analyzer">("robots-txt");
  const onSuccess = useToastSuccess();
  const onError = useToastError();

  // --- Robots.txt Generator State ---
  const [defaultRule, setDefaultRule] = useState<"allow" | "disallow">("allow");
  const [crawlDelay, setCrawlDelay] = useState<string>("none");
  const [sitemapUrl, setSitemapUrl] = useState<string>("");
  const [customRules, setCustomRules] = useState<CustomRule[]>([
    { userAgent: "Googlebot", type: "disallow", path: "/admin/" },
    { userAgent: "Bingbot", type: "disallow", path: "/temp/" }
  ]);
  const [newRuleAgent, setNewRuleAgent] = useState("*");
  const [newRuleType, setNewRuleType] = useState<"allow" | "disallow">("disallow");
  const [newRulePath, setNewRulePath] = useState("");
  const [generatedRobots, setGeneratedRobots] = useState("");
  const [copiedRobots, setCopiedRobots] = useState(false);

  // --- Robots Meta Tag Builder State ---
  const [noindex, setNoindex] = useState(false);
  const [nofollow, setNofollow] = useState(false);
  const [noarchive, setNoarchive] = useState(false);
  const [nosnippet, setNosnippet] = useState(false);
  const [noimageindex, setNoimageindex] = useState(false);
  const [notranslate, setNotranslate] = useState(false);
  
  const [maxSnippet, setMaxSnippet] = useState<"default" | "none" | "custom">("default");
  const [maxSnippetVal, setMaxSnippetVal] = useState("-1");
  const [maxImagePreview, setMaxImagePreview] = useState<"default" | "none" | "standard" | "large">("default");
  const [maxVideoPreview, setMaxVideoPreview] = useState<"default" | "none" | "custom">("default");
  const [maxVideoPreviewVal, setMaxVideoPreviewVal] = useState("-1");

  const [simulatedTitle, setSimulatedTitle] = useState("Smart Document Tools - Free Online PDF & Image Tools");
  const [simulatedUrl, setSimulatedUrl] = useState("https://valuehostings.site/en");
  const [simulatedDesc, setSimulatedDesc] = useState("Process files securely in your browser. Our tools are 100% free, fast, and keep your sensitive files private on your own device.");
  const [generatedMeta, setGeneratedMeta] = useState("");
  const [copiedMeta, setCopiedMeta] = useState(false);

  // --- Tester / Analyzer State ---
  const [testerRobots, setTesterRobots] = useState("");
  const [testerAgent, setTesterAgent] = useState("Googlebot");
  const [testerPath, setTesterPath] = useState("/admin/dashboard");
  const [testResult, setTestResult] = useState<{ allowed: boolean; reason: string } | null>(null);

  // --- Robots.txt Code Generation ---
  useEffect(() => {
    let code = "# Generated by Smart Document Tools Robots.txt Generator\n";
    code += `User-agent: *\n`;
    if (defaultRule === "disallow") {
      code += `Disallow: /\n`;
    } else {
      code += `Allow: /\n`;
    }
    if (crawlDelay !== "none") {
      code += `Crawl-delay: ${crawlDelay}\n`;
    }
    code += "\n";

    // Group rules by user agent for readability
    const agents = Array.from(new Set(customRules.map(r => r.userAgent.trim())));
    agents.forEach(agent => {
      if (!agent) return;
      code += `User-agent: ${agent}\n`;
      const agentRules = customRules.filter(r => r.userAgent.trim() === agent);
      agentRules.forEach(r => {
        const typeStr = r.type === "allow" ? "Allow" : "Disallow";
        code += `${typeStr}: ${r.path || "/"}\n`;
      });
      code += "\n";
    });

    if (sitemapUrl.trim()) {
      code += `Sitemap: ${sitemapUrl.trim()}\n`;
    }

    setGeneratedRobots(code.trim());
  }, [defaultRule, crawlDelay, sitemapUrl, customRules]);

  // Synchronize tester code with generated code initially
  useEffect(() => {
    if (generatedRobots && !testerRobots) {
      setTesterRobots(generatedRobots);
    }
  }, [generatedRobots]);

  // --- Robots Meta Tag Generation ---
  useEffect(() => {
    const parts: string[] = [];
    if (noindex) parts.push("noindex");
    if (nofollow) parts.push("nofollow");
    if (noarchive) parts.push("noarchive");
    if (nosnippet) parts.push("nosnippet");
    if (noimageindex) parts.push("noimageindex");
    if (notranslate) parts.push("notranslate");

    if (maxSnippet === "none") {
      parts.push("max-snippet:0");
    } else if (maxSnippet === "custom" && maxSnippetVal) {
      parts.push(`max-snippet:${maxSnippetVal}`);
    }

    if (maxImagePreview !== "default") {
      parts.push(`max-image-preview:${maxImagePreview}`);
    }

    if (maxVideoPreview === "none") {
      parts.push("max-video-preview:0");
    } else if (maxVideoPreview === "custom" && maxVideoPreviewVal) {
      parts.push(`max-video-preview:${maxVideoPreviewVal}`);
    }

    const content = parts.length > 0 ? parts.join(", ") : "index, follow";
    setGeneratedMeta(`<meta name="robots" content="${content}" />`);
  }, [
    noindex, nofollow, noarchive, nosnippet, noimageindex, notranslate,
    maxSnippet, maxSnippetVal, maxImagePreview, maxVideoPreview, maxVideoPreviewVal
  ]);

  // --- Add and Delete Custom Rules ---
  const handleAddRule = () => {
    if (!newRulePath.startsWith("/") && newRulePath !== "") {
      onError("Rules must start with a slash '/' or be empty");
      return;
    }
    const rulePath = newRulePath.trim() || "/";
    setCustomRules([...customRules, { 
      userAgent: newRuleAgent.trim() || "*", 
      type: newRuleType, 
      path: rulePath 
    }]);
    setNewRulePath("");
    onSuccess("Custom rule added!");
  };

  const handleDeleteRule = (index: number) => {
    const updated = [...customRules];
    updated.splice(index, 1);
    setCustomRules(updated);
    onSuccess("Rule removed!");
  };

  // --- Copy and Download Utilities ---
  const copyToClipboard = async (text: string, setCopied: (v: boolean) => void) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      onSuccess("Copied to clipboard!");
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      onError("Failed to copy");
    }
  };

  const downloadRobotsTxt = () => {
    const element = document.createElement("a");
    const file = new Blob([generatedRobots], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = "robots.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    onSuccess("Downloading robots.txt");
  };

  // --- Robots.txt Logic Tester (Client-side) ---
  const handleTestPath = () => {
    if (!testerPath.startsWith("/")) {
      onError("Test path must start with a slash '/'");
      return;
    }

    const lines = testerRobots.split("\n");
    let currentAgent = "";
    let rulesForAgent: { type: "allow" | "disallow"; pattern: string }[] = [];
    let wildcardRules: { type: "allow" | "disallow"; pattern: string }[] = [];

    // Simple robots.txt parser
    for (let line of lines) {
      line = line.split("#")[0].trim(); // Remove comments
      if (!line) continue;

      const matchAgent = line.match(/^User-agent:\s*(.+)$/i);
      if (matchAgent) {
        currentAgent = matchAgent[1].trim().toLowerCase();
        continue;
      }

      const matchAllow = line.match(/^Allow:\s*(.+)$/i);
      const matchDisallow = line.match(/^Disallow:\s*(.+)$/i);

      if (matchAllow || matchDisallow) {
        const type = matchAllow ? "allow" : "disallow";
        const pathPattern = (matchAllow ? matchAllow[1] : matchDisallow![1]).trim();
        const rule = { type: type as "allow" | "disallow", pattern: pathPattern };

        if (currentAgent === "*" || currentAgent === "") {
          wildcardRules.push(rule);
        } else if (testerAgent.toLowerCase().includes(currentAgent) || currentAgent.includes(testerAgent.toLowerCase())) {
          rulesForAgent.push(rule);
        }
      }
    }

    // Use specific agent rules if found, otherwise fall back to wildcard '*' rules
    const activeRules = rulesForAgent.length > 0 ? rulesForAgent : wildcardRules;

    if (activeRules.length === 0) {
      setTestResult({ allowed: true, reason: "No matching rules found. Crawling is allowed by default." });
      return;
    }

    // Match rules (longest matching rule takes precedence, default allow if none match)
    let bestMatch: { type: "allow" | "disallow"; pattern: string } | null = null;
    let maxMatchLength = -1;

    for (const rule of activeRules) {
      // Simple wildcard to regex conversion
      let regexStr = rule.pattern
        .replace(/[.+^${}()|[\]\\]/g, "\\$&") // Escape regex chars except * and $
        .replace(/\*/g, ".*")
        .replace(/\$$/, "");
      
      // Match from the start of the path
      if (!regexStr.startsWith("^")) {
        regexStr = "^" + regexStr;
      }

      try {
        const regex = new RegExp(regexStr);
        if (regex.test(testerPath)) {
          // Standard robots.txt states: longest rule wins
          if (rule.pattern.length > maxMatchLength) {
            maxMatchLength = rule.pattern.length;
            bestMatch = rule;
          }
        }
      } catch (e) {
        // Fallback simple prefix match if regex fails
        if (testerPath.startsWith(rule.pattern)) {
          if (rule.pattern.length > maxMatchLength) {
            maxMatchLength = rule.pattern.length;
            bestMatch = rule;
          }
        }
      }
    }

    if (bestMatch) {
      if (bestMatch.type === "allow") {
        setTestResult({
          allowed: true,
          reason: `Allowed by rule: "Allow: ${bestMatch.pattern}"`
        });
      } else {
        setTestResult({
          allowed: false,
          reason: `Blocked by rule: "Disallow: ${bestMatch.pattern}"`
        });
      }
    } else {
      setTestResult({
        allowed: true,
        reason: "No rules directly matched the path. Allowed by default."
      });
    }
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-12">
      {/* Header */}
      <div className="text-center mb-10">
        <h1 className="text-4xl font-extrabold text-gray-900 mb-4 flex items-center justify-center gap-3">
          <Settings className="w-9 h-9 text-indigo-600" /> Robots.txt & Robots Meta Tag Builder
        </h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
          Easily direct search engine crawlers, define page index policies, and simulate Google snippet previews.
        </p>
      </div>

      {/* Tabs */}
      <div className="flex justify-center mb-8 border-b border-gray-200">
        <div className="flex space-x-1 p-1 bg-gray-100 rounded-xl mb-3">
          <button
            onClick={() => setTab("robots-txt")}
            className={`px-6 py-2.5 rounded-lg text-sm font-semibold transition ${
              tab === "robots-txt" ? "bg-white text-indigo-700 shadow-sm" : "text-gray-500 hover:text-gray-950"
            }`}
          >
            Robots.txt Generator
          </button>
          <button
            onClick={() => setTab("meta-tags")}
            className={`px-6 py-2.5 rounded-lg text-sm font-semibold transition ${
              tab === "meta-tags" ? "bg-white text-indigo-700 shadow-sm" : "text-gray-500 hover:text-gray-950"
            }`}
          >
            Robots Meta Tag Builder
          </button>
          <button
            onClick={() => setTab("analyzer")}
            className={`px-6 py-2.5 rounded-lg text-sm font-semibold transition ${
              tab === "analyzer" ? "bg-white text-indigo-700 shadow-sm" : "text-gray-500 hover:text-gray-950"
            }`}
          >
            Robots.txt Tester
          </button>
        </div>
      </div>

      {/* Main content grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* LEFT COLUMN: Controls */}
        <div className="lg:col-span-7 bg-white rounded-3xl p-6 shadow-sm border border-gray-100 min-h-[500px]">
          
          {/* Tab 1: Robots.txt Configurator */}
          {tab === "robots-txt" && (
            <div>
              <h2 className="text-lg font-bold text-gray-800 mb-6">Configure Crawl Rules</h2>

              {/* Default Rule */}
              <div className="mb-6">
                <label className="block text-sm font-semibold text-gray-700 mb-2">Default rule for all bots (*):</label>
                <div className="flex gap-4">
                  <button
                    onClick={() => setDefaultRule("allow")}
                    className={`flex-1 py-3 px-4 rounded-xl border text-sm font-bold transition ${
                      defaultRule === "allow"
                        ? "bg-indigo-50 border-indigo-200 text-indigo-700 ring-2 ring-indigo-500/20"
                        : "border-gray-200 text-gray-600 hover:bg-gray-50"
                    }`}
                  >
                    Allow All Crawling
                  </button>
                  <button
                    onClick={() => setDefaultRule("disallow")}
                    className={`flex-1 py-3 px-4 rounded-xl border text-sm font-bold transition ${
                      defaultRule === "disallow"
                        ? "bg-indigo-50 border-indigo-200 text-indigo-700 ring-2 ring-indigo-500/20"
                        : "border-gray-200 text-gray-600 hover:bg-gray-50"
                    }`}
                  >
                    Disallow All Crawling
                  </button>
                </div>
              </div>

              {/* Crawl Delay */}
              <div className="mb-6">
                <label className="block text-sm font-semibold text-gray-700 mb-2">Crawl-delay:</label>
                <select
                  value={crawlDelay}
                  onChange={(e) => setCrawlDelay(e.target.value)}
                  className="w-full p-3 rounded-xl border border-gray-200 outline-none text-sm bg-gray-50 focus:bg-white focus:ring-2 focus:ring-indigo-500/20"
                >
                  <option value="none">No Delay (Default)</option>
                  <option value="1">1 second</option>
                  <option value="2">2 seconds</option>
                  <option value="5">5 seconds</option>
                  <option value="10">10 seconds</option>
                </select>
              </div>

              {/* Sitemap URL */}
              <div className="mb-6">
                <label className="block text-sm font-semibold text-gray-700 mb-2">Sitemap URL:</label>
                <input
                  type="url"
                  placeholder="https://example.com/sitemap.xml"
                  value={sitemapUrl}
                  onChange={(e) => setSitemapUrl(e.target.value)}
                  className="w-full p-3 rounded-xl border border-gray-200 outline-none text-sm focus:ring-2 focus:ring-indigo-500/20"
                />
              </div>

              {/* Custom Rules List */}
              <div className="mb-6">
                <label className="block text-sm font-semibold text-gray-700 mb-2">Specific Agent / Path Rules:</label>
                
                {/* List */}
                <div className="space-y-2 mb-4 max-h-[180px] overflow-y-auto pr-1">
                  {customRules.map((rule, idx) => (
                    <div key={idx} className="flex items-center justify-between p-3 bg-gray-50 rounded-xl border border-gray-100 text-sm">
                      <div>
                        <span className="font-semibold text-indigo-700">{rule.userAgent}</span>
                        <span className="mx-2 text-gray-400">|</span>
                        <span className={`px-2 py-0.5 rounded text-xs font-bold ${
                          rule.type === "allow" ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"
                        }`}>{rule.type.toUpperCase()}</span>
                        <span className="mx-2 text-gray-400">|</span>
                        <code className="text-gray-600 bg-gray-200/50 px-1.5 py-0.5 rounded text-xs">{rule.path}</code>
                      </div>
                      <button
                        onClick={() => handleDeleteRule(idx)}
                        className="text-gray-400 hover:text-red-500 transition p-1"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                  {customRules.length === 0 && (
                    <p className="text-xs text-gray-400 italic">No custom rules defined yet.</p>
                  )}
                </div>

                {/* Add Custom Rule Form */}
                <div className="bg-gray-50/50 p-4 rounded-2xl border border-dashed border-gray-200">
                  <span className="block text-xs font-bold text-gray-500 uppercase mb-3">Add Custom Rule</span>
                  <div className="grid grid-cols-1 sm:grid-cols-12 gap-3 mb-3">
                    <div className="sm:col-span-4">
                      <input
                        type="text"
                        placeholder="User-agent (e.g. Googlebot)"
                        value={newRuleAgent}
                        onChange={(e) => setNewRuleAgent(e.target.value)}
                        className="w-full p-2.5 rounded-lg border border-gray-200 text-xs outline-none focus:ring-2 focus:ring-indigo-500/20"
                      />
                    </div>
                    <div className="sm:col-span-3">
                      <select
                        value={newRuleType}
                        onChange={(e) => setNewRuleType(e.target.value as "allow" | "disallow")}
                        className="w-full p-2.5 rounded-lg border border-gray-200 text-xs bg-white outline-none focus:ring-2 focus:ring-indigo-500/20"
                      >
                        <option value="disallow">Disallow</option>
                        <option value="allow">Allow</option>
                      </select>
                    </div>
                    <div className="sm:col-span-5">
                      <input
                        type="text"
                        placeholder="Path (e.g. /private/)"
                        value={newRulePath}
                        onChange={(e) => setNewRulePath(e.target.value)}
                        className="w-full p-2.5 rounded-lg border border-gray-200 text-xs outline-none focus:ring-2 focus:ring-indigo-500/20"
                      />
                    </div>
                  </div>
                  <button
                    onClick={handleAddRule}
                    className="w-full py-2 bg-indigo-600 text-white rounded-lg text-xs font-bold hover:bg-indigo-700 transition flex items-center justify-center gap-1"
                  >
                    <Plus className="w-3.5 h-3.5" /> Add Rule
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Tab 2: Robots Meta Tags */}
          {tab === "meta-tags" && (
            <div>
              <h2 className="text-lg font-bold text-gray-800 mb-6">Robots Meta Tag Options</h2>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
                {/* Checkbox settings */}
                <div className="space-y-3">
                  <label className="flex items-center gap-3 p-3 rounded-xl border border-gray-100 hover:bg-gray-50 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={noindex}
                      onChange={(e) => setNoindex(e.target.checked)}
                      className="w-4 h-4 text-indigo-600 rounded border-gray-300 focus:ring-indigo-500"
                    />
                    <div>
                      <span className="block text-sm font-bold text-gray-800">noindex</span>
                      <span className="block text-xs text-gray-400">Do not display page in search results</span>
                    </div>
                  </label>

                  <label className="flex items-center gap-3 p-3 rounded-xl border border-gray-100 hover:bg-gray-50 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={nofollow}
                      onChange={(e) => setNofollow(e.target.checked)}
                      className="w-4 h-4 text-indigo-600 rounded border-gray-300 focus:ring-indigo-500"
                    />
                    <div>
                      <span className="block text-sm font-bold text-gray-800">nofollow</span>
                      <span className="block text-xs text-gray-400">Do not follow links on this page</span>
                    </div>
                  </label>

                  <label className="flex items-center gap-3 p-3 rounded-xl border border-gray-100 hover:bg-gray-50 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={nosnippet}
                      onChange={(e) => setNosnippet(e.target.checked)}
                      className="w-4 h-4 text-indigo-600 rounded border-gray-300 focus:ring-indigo-500"
                    />
                    <div>
                      <span className="block text-sm font-bold text-gray-800">nosnippet</span>
                      <span className="block text-xs text-gray-400">Exclude snippet from search results</span>
                    </div>
                  </label>
                </div>

                <div className="space-y-3">
                  <label className="flex items-center gap-3 p-3 rounded-xl border border-gray-100 hover:bg-gray-50 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={noarchive}
                      onChange={(e) => setNoarchive(e.target.checked)}
                      className="w-4 h-4 text-indigo-600 rounded border-gray-300 focus:ring-indigo-500"
                    />
                    <div>
                      <span className="block text-sm font-bold text-gray-800">noarchive</span>
                      <span className="block text-xs text-gray-400">Do not show cached link in search</span>
                    </div>
                  </label>

                  <label className="flex items-center gap-3 p-3 rounded-xl border border-gray-100 hover:bg-gray-50 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={noimageindex}
                      onChange={(e) => setNoimageindex(e.target.checked)}
                      className="w-4 h-4 text-indigo-600 rounded border-gray-300 focus:ring-indigo-500"
                    />
                    <div>
                      <span className="block text-sm font-bold text-gray-800">noimageindex</span>
                      <span className="block text-xs text-gray-400">Do not index images on this page</span>
                    </div>
                  </label>

                  <label className="flex items-center gap-3 p-3 rounded-xl border border-gray-100 hover:bg-gray-50 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={notranslate}
                      onChange={(e) => setNotranslate(e.target.checked)}
                      className="w-4 h-4 text-indigo-600 rounded border-gray-300 focus:ring-indigo-500"
                    />
                    <div>
                      <span className="block text-sm font-bold text-gray-800">notranslate</span>
                      <span className="block text-xs text-gray-400">Do not translate page in search</span>
                    </div>
                  </label>
                </div>
              </div>

              {/* Advanced Attributes */}
              <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">Advanced Parameters</h3>
              <div className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-12 gap-3 items-center">
                  <label className="sm:col-span-4 text-sm text-gray-600 font-semibold">Max Snippet Length:</label>
                  <div className="sm:col-span-4">
                    <select
                      value={maxSnippet}
                      onChange={(e) => setMaxSnippet(e.target.value as any)}
                      className="w-full p-2.5 rounded-lg border border-gray-200 text-xs bg-white"
                    >
                      <option value="default">Default</option>
                      <option value="none">None (0 chars)</option>
                      <option value="custom">Custom Character Count</option>
                    </select>
                  </div>
                  {maxSnippet === "custom" && (
                    <div className="sm:col-span-4">
                      <input
                        type="number"
                        placeholder="Characters"
                        value={maxSnippetVal}
                        onChange={(e) => setMaxSnippetVal(e.target.value)}
                        className="w-full p-2 rounded-lg border border-gray-200 text-xs"
                      />
                    </div>
                  )}
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-12 gap-3 items-center">
                  <label className="sm:col-span-4 text-sm text-gray-600 font-semibold">Max Image Preview:</label>
                  <div className="sm:col-span-8">
                    <select
                      value={maxImagePreview}
                      onChange={(e) => setMaxImagePreview(e.target.value as any)}
                      className="w-full p-2.5 rounded-lg border border-gray-200 text-xs bg-white"
                    >
                      <option value="default">Default (Google determines)</option>
                      <option value="none">None (No preview)</option>
                      <option value="standard">Standard (Standard size)</option>
                      <option value="large">Large (Large image preview)</option>
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-12 gap-3 items-center">
                  <label className="sm:col-span-4 text-sm text-gray-600 font-semibold">Max Video Preview:</label>
                  <div className="sm:col-span-4">
                    <select
                      value={maxVideoPreview}
                      onChange={(e) => setMaxVideoPreview(e.target.value as any)}
                      className="w-full p-2.5 rounded-lg border border-gray-200 text-xs bg-white"
                    >
                      <option value="default">Default</option>
                      <option value="none">None (0 seconds)</option>
                      <option value="custom">Custom Seconds</option>
                    </select>
                  </div>
                  {maxVideoPreview === "custom" && (
                    <div className="sm:col-span-4">
                      <input
                        type="number"
                        placeholder="Seconds"
                        value={maxVideoPreviewVal}
                        onChange={(e) => setMaxVideoPreviewVal(e.target.value)}
                        className="w-full p-2 rounded-lg border border-gray-200 text-xs"
                      />
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* Tab 3: Robots.txt Tester */}
          {tab === "analyzer" && (
            <div>
              <h2 className="text-lg font-bold text-gray-800 mb-4">Analyze Rules & Test URL Paths</h2>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-xs font-bold text-gray-500 uppercase mb-2">Robots.txt Rules to evaluate:</label>
                  <textarea
                    value={testerRobots}
                    onChange={(e) => setTesterRobots(e.target.value)}
                    rows={8}
                    className="w-full p-3 font-mono text-xs rounded-xl border border-gray-200 outline-none resize-none bg-gray-50 focus:bg-white"
                    placeholder="Paste robots.txt rules here..."
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-12 gap-4">
                  <div className="sm:col-span-4">
                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1.5">User-agent:</label>
                    <input
                      type="text"
                      value={testerAgent}
                      onChange={(e) => setTesterAgent(e.target.value)}
                      className="w-full p-2.5 rounded-lg border border-gray-200 text-sm outline-none"
                      placeholder="e.g. Googlebot"
                    />
                  </div>
                  <div className="sm:col-span-8">
                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1.5">Path to test:</label>
                    <input
                      type="text"
                      value={testerPath}
                      onChange={(e) => setTesterPath(e.target.value)}
                      className="w-full p-2.5 rounded-lg border border-gray-200 text-sm outline-none"
                      placeholder="e.g. /admin/settings"
                    />
                  </div>
                </div>

                <button
                  onClick={handleTestPath}
                  className="w-full py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-bold transition flex items-center justify-center gap-2"
                >
                  <RefreshCw className="w-4 h-4" /> Run Crawl Eligibility Test
                </button>

                {/* Tester output box */}
                {testResult && (
                  <div className={`p-4 rounded-2xl border flex items-start gap-4 transition ${
                    testResult.allowed 
                      ? "bg-green-50 border-green-200 text-green-800" 
                      : "bg-red-50 border-red-200 text-red-800"
                  }`}>
                    {testResult.allowed ? (
                      <ShieldCheck className="w-8 h-8 text-green-600 shrink-0" />
                    ) : (
                      <ShieldAlert className="w-8 h-8 text-red-600 shrink-0" />
                    )}
                    <div>
                      <h4 className="font-bold text-sm">
                        {testResult.allowed ? "ALLOWED" : "BLOCKED / DISALLOWED"}
                      </h4>
                      <p className="text-xs mt-1 text-gray-600">{testResult.reason}</p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* RIGHT COLUMN: Output Preview & Live Simulator */}
        <div className="lg:col-span-5 space-y-6">
          
          {/* Box 1: Output code snippet */}
          <div className="bg-slate-900 rounded-3xl p-5 shadow-lg border border-slate-800 flex flex-col h-fit relative text-slate-300">
            <div className="flex justify-between items-center mb-3 pb-3 border-b border-slate-800">
              <span className="font-bold text-xs text-slate-400 tracking-widest uppercase flex items-center gap-2">
                <FileText className="w-4 h-4 text-indigo-400" />
                {tab === "robots-txt" || tab === "analyzer" ? "Generated robots.txt" : "Robots Meta Tag"}
              </span>
              <div className="flex gap-2">
                {(tab === "robots-txt" || tab === "analyzer") ? (
                  <>
                    <button
                      onClick={() => copyToClipboard(generatedRobots, setCopiedRobots)}
                      className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-white transition"
                      title="Copy content"
                    >
                      <Copy className="w-4 h-4" />
                    </button>
                    <button
                      onClick={downloadRobotsTxt}
                      className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-white transition"
                      title="Download file"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </>
                ) : (
                  <button
                    onClick={() => copyToClipboard(generatedMeta, setCopiedMeta)}
                    className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-white transition"
                    title="Copy meta tag"
                  >
                    <Copy className="w-4 h-4" />
                  </button>
                )}
              </div>
            </div>
            <pre className="font-mono text-xs overflow-x-auto whitespace-pre p-2 bg-slate-950/60 rounded-xl leading-relaxed max-h-[220px] select-all">
              {tab === "robots-txt" || tab === "analyzer" ? generatedRobots : generatedMeta}
            </pre>
          </div>

          {/* Box 2: Visual Google Search Snippet Simulator */}
          <div className="bg-white rounded-3xl p-6 shadow-sm border border-gray-100">
            <div className="flex items-center justify-between mb-4 border-b border-gray-50 pb-2">
              <span className="font-bold text-xs text-gray-500 uppercase tracking-wider flex items-center gap-1.5">
                <Eye className="w-4 h-4 text-indigo-500" />
                Google Search Result Simulator
              </span>
            </div>

            {/* Inputs for simulation fields */}
            <div className="space-y-2.5 mb-5">
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase">Simulated Page Title</label>
                <input
                  type="text"
                  value={simulatedTitle}
                  onChange={(e) => setSimulatedTitle(e.target.value)}
                  className="w-full px-2.5 py-1 text-xs border border-gray-200 rounded-md focus:outline-indigo-500"
                />
              </div>
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase">Simulated URL</label>
                <input
                  type="text"
                  value={simulatedUrl}
                  onChange={(e) => setSimulatedUrl(e.target.value)}
                  className="w-full px-2.5 py-1 text-xs border border-gray-200 rounded-md focus:outline-indigo-500"
                />
              </div>
              <div>
                <label className="block text-[10px] font-bold text-gray-400 uppercase">Simulated Meta Description</label>
                <textarea
                  value={simulatedDesc}
                  onChange={(e) => setSimulatedDesc(e.target.value)}
                  rows={2}
                  className="w-full px-2.5 py-1 text-xs border border-gray-200 rounded-md focus:outline-indigo-500 resize-none"
                />
              </div>
            </div>

            {/* Simulated Search Card */}
            <div className="border border-gray-200/80 rounded-2xl p-4 bg-gray-50/30">
              <span className="block text-[10px] font-bold text-gray-400 uppercase mb-2">Live Snippet Preview:</span>
              
              {noindex ? (
                <div className="border-2 border-dashed border-red-200 bg-red-50/50 p-4 rounded-xl text-center">
                  <ShieldAlert className="w-8 h-8 text-red-500 mx-auto mb-2 opacity-80" />
                  <p className="text-xs font-bold text-red-800">Page Excluded From Search Results</p>
                  <p className="text-[10px] text-red-600 mt-1">
                    Because `noindex` is active, Googlebot will remove this page from indexing. It will not appear in search results at all.
                  </p>
                </div>
              ) : nosnippet ? (
                <div className="space-y-1">
                  {/* Google snippet structure with no snippet content */}
                  <div className="flex items-center gap-1.5">
                    <span className="w-5 h-5 rounded-full bg-gray-200 flex items-center justify-center text-[10px] font-bold text-gray-500">S</span>
                    <div>
                      <span className="block text-[11px] text-gray-600 leading-tight">Smart Document Tools</span>
                      <span className="block text-[10px] text-gray-400 leading-none">{simulatedUrl}</span>
                    </div>
                  </div>
                  <h3 className="text-lg text-[#1a0dab] hover:underline font-normal cursor-pointer leading-snug">
                    {simulatedTitle}
                  </h3>
                  {/* Missing snippet message */}
                  <p className="text-xs text-[#4d5156] leading-relaxed italic bg-yellow-50/50 p-2.5 rounded-lg border border-yellow-100">
                    No information is available for this page.
                  </p>
                  <p className="text-[10px] text-gray-400 mt-2 block">
                    * Because `nosnippet` is active, Google will display the URL but exclude description text or visual reviews.
                  </p>
                </div>
              ) : (
                <div className="space-y-1">
                  {/* Standard snippet */}
                  <div className="flex items-center gap-1.5">
                    <span className="w-5 h-5 rounded-full bg-gray-200 flex items-center justify-center text-[10px] font-bold text-gray-500">S</span>
                    <div>
                      <span className="block text-[11px] text-gray-600 leading-tight">Smart Document Tools</span>
                      <span className="block text-[10px] text-gray-400 leading-none">{simulatedUrl}</span>
                    </div>
                  </div>
                  <h3 className="text-lg text-[#1a0dab] hover:underline font-normal cursor-pointer leading-snug">
                    {simulatedTitle}
                  </h3>
                  <p className="text-xs text-[#4d5156] leading-relaxed">
                    {simulatedDesc}
                  </p>
                </div>
              )}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
